server:
  port: 8080

spring:
  application:
    name: ov-ndov-zmq-service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:group}

ov:
  url: tcp://pubsub.besteffort.ndovloket.nl:7658